[[headers]]
  for = "/fonts/*"
  [headers.values]
    cache-control = "max-age=31556952"

[[headers]]
  for = "/*"
  [headers.values]
    cache-control = "max-age=86400"

[build]
  publish = "build"
  command = "rm -rf build && bundle exec middleman build"

[build.environment]
  RUBY_VERSION = "3.3.10"

[build.processing]
  skip_processing = true
