[[headers]]
  for = "/fonts/*"
  [headers.values]
    cache-control = "max-age=31556952"

[[headers]]
  for = "/*"
  [headers.values]
    cache-control = "max-age=86400"

[build.processing]
    skip_processing = true
